name: Backend Continuous Deployment

on:
  push:
    branches: [main]
    paths:
      - "starter/backend/**"
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        run: |
          docker build -t $ECR_BACKEND_REPO:$IMAGE_TAG starter/backend
          docker push $ECR_BACKEND_REPO:$IMAGE_TAG
        env:
          ECR_BACKEND_REPO: ${{ secrets.ECR_BACKEND_REPO }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          mv kustomize /usr/local/bin/

      - name: Deploy to EKS
        run: |
          cd starter/backend/k8s
          kustomize edit set image backend=${{ secrets.ECR_BACKEND_REPO }}:$IMAGE_TAG
          kustomize build | kubectl apply -f -