name: Frontend CD

on:
  push:
    branches: [main]
    paths:
      - "starter/frontend/**"

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        run: |
          docker build -t $ECR_FRONTEND_REPO:$IMAGE_TAG starter/frontend
          docker push $ECR_FRONTEND_REPO:$IMAGE_TAG
        env:
          ECR_FRONTEND_REPO: ${{ secrets.ECR_FRONTEND_REPO }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Deploy to EKS
        run: |
          cd starter/frontend/k8s
          kustomize edit set image frontend=${{ secrets.ECR_FRONTEND_REPO }}:$IMAGE_TAG
          kustomize build | kubectl apply -f -